# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-10-06 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_userprofile'),
    ]

    operations = [


    ]
