# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-10-06 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20181006_0348'),
    ]

    operations = [

    ]
