# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-10-08 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20181008_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='file',
            field=models.FileField(blank=True, upload_to=b'upload_file_from_page'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='txt',
            field=models.TextField(blank=True),
        ),
    ]
